using Bogus;
using Demo.Models.Props21;

namespace Demo.Fakers.Props21;

public class Faker
{
    public Faker<Root> RootFaker { get; } = new Faker<Root>()
        .RuleFor(o => o.RootProp1, s => s.Lorem.Word())
        .RuleFor(o => o.RootProp2, s => s.Lorem.Word())
        .RuleFor(o => o.RootProp3, s => s.Random.Int())
        .RuleFor(o => o.RootProp4, s => s.Random.Int())
        ;

    public Faker<ChildA> ChildAFaker { get; } = new Faker<ChildA>()
        .RuleFor(o => o.RootProp1, s => s.Lorem.Word())
        .RuleFor(o => o.RootProp2, s => s.Lorem.Word())
        .RuleFor(o => o.RootProp3, s => s.Random.Int())
        .RuleFor(o => o.RootProp4, s => s.Random.Int())
        .RuleFor(o => o.ChildAProp1, s => s.Lorem.Word())
        .RuleFor(o => o.ChildAProp2, s => s.Lorem.Word())
        .RuleFor(o => o.ChildAProp3, s => s.Random.Int())
        .RuleFor(o => o.ChildAProp4, s => s.Lorem.Word())
        .RuleFor(o => o.ChildAProp5, s => s.Random.Int())
        .RuleFor(o => o.ChildAProp6, s => s.Lorem.Word())
        .RuleFor(o => o.ChildAProp7, s => s.Random.Int())
        .RuleFor(o => o.ChildAProp8, s => s.Lorem.Word())
        .RuleFor(o => o.ChildAProp9, s => s.Random.Int())
        .RuleFor(o => o.ChildAProp10, s => s.Lorem.Word())
        .RuleFor(o => o.ChildAProp11, s => s.Random.Int())
        .RuleFor(o => o.ChildAProp12, s => s.Lorem.Word())
        .RuleFor(o => o.ChildAProp13, s => s.Random.Int())
        .RuleFor(o => o.ChildAProp14, s => s.Lorem.Word())
        .RuleFor(o => o.ChildAProp15, s => s.Random.Int())
        .RuleFor(o => o.ChildAProp16, s => s.Lorem.Word())
        .RuleFor(o => o.ChildAProp17, s => s.Random.Int())
        .RuleFor(o => o.ChildAProp18, s => s.Lorem.Word())
        .RuleFor(o => o.ChildAProp19, s => s.Random.Int())
        .RuleFor(o => o.ChildAProp20, s => s.Lorem.Word())
        .RuleFor(o => o.ChildAProp21, s => s.Random.Int())
        ;

    public Faker<ChildB> ChildBFaker { get; } = new Faker<ChildB>()
        .RuleFor(o => o.RootProp1, s => s.Lorem.Word())
        .RuleFor(o => o.RootProp2, s => s.Lorem.Word())
        .RuleFor(o => o.RootProp3, s => s.Random.Int())
        .RuleFor(o => o.RootProp4, s => s.Random.Int())
        .RuleFor(o => o.ChildBProp1, s => s.Lorem.Word())
        .RuleFor(o => o.ChildBProp2, s => s.Lorem.Word())
        .RuleFor(o => o.ChildBProp3, s => s.Random.Int())
        .RuleFor(o => o.ChildBProp4, s => s.Lorem.Word())
        .RuleFor(o => o.ChildBProp5, s => s.Random.Int())
        .RuleFor(o => o.ChildBProp6, s => s.Lorem.Word())
        .RuleFor(o => o.ChildBProp7, s => s.Random.Int())
        .RuleFor(o => o.ChildBProp8, s => s.Lorem.Word())
        .RuleFor(o => o.ChildBProp9, s => s.Random.Int())
        .RuleFor(o => o.ChildBProp10, s => s.Lorem.Word())
        .RuleFor(o => o.ChildBProp11, s => s.Random.Int())
        .RuleFor(o => o.ChildBProp12, s => s.Lorem.Word())
        .RuleFor(o => o.ChildBProp13, s => s.Random.Int())
        .RuleFor(o => o.ChildBProp14, s => s.Lorem.Word())
        .RuleFor(o => o.ChildBProp15, s => s.Random.Int())
        .RuleFor(o => o.ChildBProp16, s => s.Lorem.Word())
        .RuleFor(o => o.ChildBProp17, s => s.Random.Int())
        .RuleFor(o => o.ChildBProp18, s => s.Lorem.Word())
        .RuleFor(o => o.ChildBProp19, s => s.Random.Int())
        .RuleFor(o => o.ChildBProp20, s => s.Lorem.Word())
        .RuleFor(o => o.ChildBProp21, s => s.Random.Int())
        ;

    public Faker<ChildC> ChildCFaker { get; } = new Faker<ChildC>()
        .RuleFor(o => o.RootProp1, s => s.Lorem.Word())
        .RuleFor(o => o.RootProp2, s => s.Lorem.Word())
        .RuleFor(o => o.RootProp3, s => s.Random.Int())
        .RuleFor(o => o.RootProp4, s => s.Random.Int())
        .RuleFor(o => o.ChildCProp1, s => s.Lorem.Word())
        .RuleFor(o => o.ChildCProp2, s => s.Lorem.Word())
        .RuleFor(o => o.ChildCProp3, s => s.Random.Int())
        .RuleFor(o => o.ChildCProp4, s => s.Lorem.Word())
        .RuleFor(o => o.ChildCProp5, s => s.Random.Int())
        .RuleFor(o => o.ChildCProp6, s => s.Lorem.Word())
        .RuleFor(o => o.ChildCProp7, s => s.Random.Int())
        .RuleFor(o => o.ChildCProp8, s => s.Lorem.Word())
        .RuleFor(o => o.ChildCProp9, s => s.Random.Int())
        .RuleFor(o => o.ChildCProp10, s => s.Lorem.Word())
        .RuleFor(o => o.ChildCProp11, s => s.Random.Int())
        .RuleFor(o => o.ChildCProp12, s => s.Lorem.Word())
        .RuleFor(o => o.ChildCProp13, s => s.Random.Int())
        .RuleFor(o => o.ChildCProp14, s => s.Lorem.Word())
        .RuleFor(o => o.ChildCProp15, s => s.Random.Int())
        .RuleFor(o => o.ChildCProp16, s => s.Lorem.Word())
        .RuleFor(o => o.ChildCProp17, s => s.Random.Int())
        .RuleFor(o => o.ChildCProp18, s => s.Lorem.Word())
        .RuleFor(o => o.ChildCProp19, s => s.Random.Int())
        .RuleFor(o => o.ChildCProp20, s => s.Lorem.Word())
        .RuleFor(o => o.ChildCProp21, s => s.Random.Int())
        ;
}